const ROSTER_URL='https://fausports.com/sports/football/roster';
const BASE='https://fausports.com';
const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const abs=u=>{if(!u)return'';if(u.startsWith('//'))return'https:'+u;if(u.startsWith('/'))return BASE+u;return u};
const norm=s=>strip(s).toLowerCase().replace(/[^a-z0-9]/g,'');
function first(re,s){const m=String(s||'').match(re);return m?strip(m[1]||m[2]||''):''}
function imageAttrs(tag=''){const out=[];for(const a of ['data-src','data-original','data-lazy-src','data-lazy','data-image','src']){const m=tag.match(new RegExp(`${a}=["']([^"']+)["']`,'i'));if(m?.[1])out.push(abs(m[1]))}const ss=tag.match(/srcset=["']([^"']+)["']/i);if(ss?.[1])ss[1].split(',').forEach(x=>out.push(abs(x.trim().split(/\s+/)[0])));return [...new Set(out)].filter(Boolean)}
function score(tag,url,name,dist=0){const t=String(tag).toLowerCase(),u=String(url).toLowerCase();let s=0;if(norm(t).includes(norm(name)))s+=180;if(/sidearm-roster-player-image|roster-player-image|sidearm-roster-player-photo/.test(t))s+=140;if(/images\.sidearmdev\.com|cloudfront\.net/.test(u))s+=50;if(/roster|player|football|headshot|portrait/.test(u))s+=35;if(/logo|wordmark|header|footer|sponsor|icon|placeholder|default|facility|stadium|story/.test(u))s-=220;s-=Math.min(100,Math.floor(dist/70));return s}
function bestImageNear(html,idx,name){const start=Math.max(0,idx-5000),end=Math.min(html.length,idx+6000),chunk=html.slice(start,end),c=[];for(const m of chunk.matchAll(/<img\b[^>]*>/gi)){const tag=m[0],dist=Math.abs((start+(m.index||0))-idx);for(const u of imageAttrs(tag))c.push({u,s:score(tag,u,name,dist)})}c.sort((a,b)=>b.s-a.s);return c.find(x=>x.s>20)?.u||''}
function around(html,idx){return html.slice(Math.max(0,idx-2400),Math.min(html.length,idx+3800))}
export default async function handler(req,res){try{const r=await fetch(`${ROSTER_URL}?v=${Date.now()}`,{cache:'no-store',headers:{'user-agent':'Mozilla/5.0','accept':'text/html,application/xhtml+xml'}});if(!r.ok)return res.status(r.status).json({error:`FAU roster returned ${r.status}`});const html=await r.text(),players=[],seen=new Set();const re=/<a[^>]+href=["']([^"']*\/sports\/football\/roster\/[^"'#?]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const profile=abs(m[1]);if(!profile||seen.has(profile))continue;let name=strip(m[2]);const chunk=around(html,m.index);if(!name||name.length>80||/full bio|view/i.test(name))name=first(/class=["'][^"']*sidearm-roster-player-name[^"']*["'][\s\S]*?<a[^>]*>([\s\S]*?)<\/a>/i,chunk)||first(/<h3[^>]*>([\s\S]*?)<\/h3>/i,chunk);if(!name||/coaches|staff|schedule|roster/i.test(name))continue;const number=first(/class=["'][^"']*sidearm-roster-player-jersey-number[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk);const position=first(/class=["'][^"']*sidearm-roster-player-position-short[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk)||first(/class=["'][^"']*sidearm-roster-player-position-long-short[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk);const height=first(/class=["'][^"']*sidearm-roster-player-height[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk);const weight=first(/class=["'][^"']*sidearm-roster-player-weight[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk).replace(/\s*lbs?\.?$/i,'');const cls=first(/class=["'][^"']*sidearm-roster-player-academic-year[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk);const hometown=first(/class=["'][^"']*sidearm-roster-player-hometown[^"']*["'][^>]*>([\s\S]*?)<\//i,chunk);const image=bestImageNear(html,m.index,name);players.push({number,name,position,height,weight,class:cls,hometown,profile,image,source:'Official Florida Atlantic 2026 roster'});seen.add(profile)}const uniq=new Map();for(const p of players){const k=norm(p.name)+'|'+String(p.number||'')+'|'+String(p.position||'');if(p.name&&!uniq.has(k))uniq.set(k,p)}const out=[...uniq.values()];res.setHeader('Cache-Control','no-store, max-age=0');res.status(200).json({season:2026,players:out,source:ROSTER_URL,count:out.length})}catch(e){res.status(500).json({error:e?.message||'FAU roster scrape failed'})}}
